version: "3"

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=exchange_rate_db
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=djangouser

  web:
    build: .
    container_name: web
    ports:
      - 8000:8000
      - 6800:6800
      - 5000:5000
    depends_on:
      - db