version: "3"

services:
  db:
    image: postgres:latest
    container_name: db
    expose:
      - 5432
    ports:
      - 6543:5432
    environment:
      - POSTGRES_DB=exchange_rate_db
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=djangouser

#  web:
#    container_name: web
#    expose:
#      - 8000
#    ports:
#      - 8000:8000
#
#  scrapy:
#    container_name: scrapy
#    expose:
#      - 5000
#    ports:
#      - 5000:5000