# Generated by Django 2.2.1 on 2019-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=20)),
                ('rate', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
