# Generated by Django 2.2.1 on 2019-05-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='rate',
            new_name='rate_buy',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='rate_sell',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
